apiVersion: v1
kind: Service
metadata:
  name: foxctl
  namespace: foxctl
  labels:
    app.kubernetes.io/name: foxctl
    app.kubernetes.io/component: core
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: health
    protocol: TCP
  selector:
    app.kubernetes.io/name: foxctl
    app.kubernetes.io/component: core
