package main

import "fmt"

func printHelp() {
	fmt.Println("agentctl-viewer - TUI for viewing agentctl jobs and tasks")
	fmt.Println()
	fmt.Println("Usage:")
	fmt.Println("  agentctl-viewer [flags]")
	fmt.Println()
	fmt.Println("Interactive Views:")
	fmt.Println("  (default)              Jobs list with detail tabs")
	fmt.Println("  --tasks                Tasks recommendation view")
	fmt.Println("  --insights             Insights dashboard (keystones, bottlenecks, cycles)")
	fmt.Println("  --mailbox <actor>      Mailbox messages for an actor")
	fmt.Println("  --reservations         File reservations view")
	fmt.Println("  --stats                Job statistics view")
	fmt.Println("  --blackboard           Blackboard browser view")
	fmt.Println("  --sqlite               SQLite database browser")
	fmt.Println()
	fmt.Println("Robot Flags (JSON output for AI agents):")
	fmt.Println("  --robot-help           Show AI agent help")
	fmt.Println("  --robot-jobs           Output jobs list as JSON")
	fmt.Println("  --robot-job <id>       Output single job detail as JSON")
	fmt.Println("  --robot-tasks          Output task list as JSON")
	fmt.Println("  --robot-insights       Output task graph insights as JSON")
	fmt.Println("  --robot-plan           Output execution plan as JSON")
	fmt.Println("  --robot-graph          Output dependency graph as JSON")
	fmt.Println("  --robot-priority       Output priority recommendations as JSON")
	fmt.Println("  --robot-mailbox <actor> Output mailbox messages as JSON")
	fmt.Println("  --robot-reservations   Output file reservations as JSON")
	fmt.Println("  --robot-stats          Output job statistics as JSON")
	fmt.Println("  --robot-blackboard     Output blackboard records as JSON")
	fmt.Println("  --robot-sqlite         Output SQLite database info as JSON")
	fmt.Println()
	fmt.Println("Filters:")
	fmt.Println("  --workspace <path>     Filter by workspace path")
	fmt.Println("  --state <state>        Filter by job state (ok, error, running, queued)")
	fmt.Println("  --limit <n>            Limit number of results (default: 50)")
	fmt.Println("  --recipe <name>        Apply recipe filter (actionable, blocked, recent, errors)")
	fmt.Println("  --bb-ns <namespace>    Blackboard namespace (default: default)")
	fmt.Println("  --bb-topic <topic>     Blackboard topic filter")
	fmt.Println("  --db <name>            SQLite database name (for --robot-sqlite)")
	fmt.Println("  --table <name>         SQLite table name (for --robot-sqlite)")
	fmt.Println()
	fmt.Println("Navigation (in TUI):")
	fmt.Println("  1-8                    Direct jump to view:")
	fmt.Println("                           1=Jobs, 2=Tasks, 3=Insights, 4=Mailbox,")
	fmt.Println("                           5=Reservations, 6=Stats, 7=Blackboard, 8=SQLite")
	fmt.Println("  tab, ]                 Next view")
	fmt.Println("  [                      Previous view")
	fmt.Println("  up/k, down/j           Navigate list items")
	fmt.Println("  enter                  View details of selected item")
	fmt.Println("  esc                    Back to list")
	fmt.Println("  r                      Refresh current view")
	fmt.Println("  q                      Quit")
	fmt.Println()
	fmt.Println("Actions (in TUI):")
	fmt.Println("  c                      Cancel job (Jobs view)")
	fmt.Println("  d                      Mark task complete (Tasks view)")
	fmt.Println("  s                      Set task as active (Tasks view)")
	fmt.Println("  a                      Cycle actor (Mailbox view)")
	fmt.Println("  x                      Ack message (Mailbox) / Release reservation (Reservations)")
	fmt.Println()
	fmt.Println("In Job Detail View:")
	fmt.Println("  tab, 1-4               Switch detail tabs (Info, Result, Stderr, Artifacts)")
	fmt.Println("  esc                    Back to job list")
	fmt.Println()
	fmt.Println("In SQLite Browser View:")
	fmt.Println("  h/l, left/right        Switch between panes (Databases → Tables → Data)")
	fmt.Println("  enter                  Select database/table, view row detail")
	fmt.Println("  esc                    Go back one level")
	fmt.Println("  i                      Show table schema (CREATE TABLE)")
	fmt.Println("  r                      Refresh current pane")
}

func printRobotHelp() {
	fmt.Println("agentctl-viewer Robot Interface")
	fmt.Println("================================")
	fmt.Println()
	fmt.Println("These flags output structured JSON for AI agent consumption.")
	fmt.Println()
	fmt.Println("Job Operations:")
	fmt.Println("  --robot-jobs")
	fmt.Println("      Output list of jobs with state summary.")
	fmt.Println("      Key fields: id, command, state, created_at, error")
	fmt.Println("      Summary includes: total, ok, error, running, queued counts")
	fmt.Println()
	fmt.Println("  --robot-job <job-id>")
	fmt.Println("      Output single job with full detail.")
	fmt.Println("      Key fields: result_data, stderr, artifacts, error")
	fmt.Println()
	fmt.Println("Task Operations:")
	fmt.Println("  --robot-tasks")
	fmt.Println("      Output task list from todo store.")
	fmt.Println()
	fmt.Println("  --robot-insights")
	fmt.Println("      Output task graph insights as JSON.")
	fmt.Println("      Key fields: nodes (pagerank, critical_path), cycles, topological_order")
	fmt.Println()
	fmt.Println("  --robot-plan")
	fmt.Println("      Output task execution plan as JSON.")
	fmt.Println("      Shows recommended task order based on overseer scoring.")
	fmt.Println("      Combines: 30% critical path, 20% PageRank, 25% admin mail,")
	fmt.Println("                15% overseer mail, 10% recency")
	fmt.Println()
	fmt.Println("  --robot-graph")
	fmt.Println("      Output task dependency graph as JSON.")
	fmt.Println("      Key fields: node_count, cycle_count, topological_order, top_nodes")
	fmt.Println("      Top nodes include PageRank, critical path score, in/out degree")
	fmt.Println()
	fmt.Println("  --robot-priority")
	fmt.Println("      Output priority recommendations with reasoning as JSON.")
	fmt.Println("      Key fields: task_id, score, confidence, reasoning")
	fmt.Println("      Reasoning explains why each task is prioritized")
	fmt.Println()
	fmt.Println("  --robot-mailbox <actor>")
	fmt.Println("      Output mailbox messages for an actor as JSON.")
	fmt.Println("      Key fields: sender, recipient, subject, body, priority, status")
	fmt.Println("      Summary includes: total, unread, urgent counts")
	fmt.Println()
	fmt.Println("  --robot-reservations")
	fmt.Println("      Output active file reservations as JSON.")
	fmt.Println("      Key fields: path, holder, mode (exclusive/shared), expires_at")
	fmt.Println("      Summary includes: total, exclusive, shared, by_holder counts")
	fmt.Println()
	fmt.Println("SQLite Operations:")
	fmt.Println("  --robot-sqlite")
	fmt.Println("      Output SQLite database info as JSON.")
	fmt.Println("      Without --db: Lists all databases in ~/.agentctl")
	fmt.Println("      With --db: Lists tables in that database")
	fmt.Println("      With --db and --table: Outputs rows from that table")
	fmt.Println()
	fmt.Println("  --robot-sqlite --db <name>")
	fmt.Println("      List tables in a specific database.")
	fmt.Println("      Key fields: name, row_count")
	fmt.Println()
	fmt.Println("  --robot-sqlite --db <name> --table <table>")
	fmt.Println("      Output rows from a specific table.")
	fmt.Println("      Key fields: columns, rows, total_rows")
	fmt.Println("      Use --limit to control number of rows (default: 50, max: 1000)")
	fmt.Println()
	fmt.Println("Filters:")
	fmt.Println("  --workspace <path>   Filter by workspace path")
	fmt.Println("  --state <state>      Filter jobs by state (ok, error, running, queued)")
	fmt.Println("  --limit <n>          Limit results (default: 50)")
	fmt.Println("  --recipe <name>      Apply recipe filter (actionable, blocked, recent, errors)")
}
