apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foxctl-local-cache
  namespace: foxctl
  labels:
    app.kubernetes.io/name: foxctl
    app.kubernetes.io/component: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
