// Code generated by tui generate. DO NOT EDIT.
// Source: shell.gsx

package tui

import (
	"fmt"
	"strings"

	tui "github.com/grindlemire/go-tui"
)

type Shell struct {
	state           *tui.State[ShellState]
	transcriptFocus *tui.State[bool]
	composerFocus   *tui.State[bool]
	railFocus       *tui.State[bool]
	workersFocus    *tui.State[bool]
	focus           *tui.FocusGroup
}

func NewShell(initial ShellState) *Shell {
	transcriptFocus := tui.NewState(true)
	composerFocus := tui.NewState(false)
	railFocus := tui.NewState(false)
	workersFocus := tui.NewState(false)

	return &Shell{
		state:           tui.NewState(initial),
		transcriptFocus: transcriptFocus,
		composerFocus:   composerFocus,
		railFocus:       railFocus,
		workersFocus:    workersFocus,
		focus:           tui.MustNewFocusGroup(transcriptFocus, composerFocus, railFocus, workersFocus),
	}
}

func (s *Shell) KeyMap() tui.KeyMap {
	keyMap := append(tui.KeyMap{}, s.focus.KeyMap()...)
	keyMap = append(keyMap, stopBindings()...)
	keyMap = append(keyMap,
		tui.On(tui.Rune('m').Ctrl(), func(ke tui.KeyEvent) { s.setRail(RailMemory) }),
		tui.On(tui.Rune('y').Ctrl(), func(ke tui.KeyEvent) { s.setRail(RailContinuity) }),
		tui.On(tui.Rune('w').Ctrl(), func(ke tui.KeyEvent) { s.setRail(RailWorkers) }),
		tui.On(tui.Rune('b').Ctrl(), func(ke tui.KeyEvent) { s.setRail(RailTask) }),
		tui.On(tui.KeyRight, func(ke tui.KeyEvent) { s.cycleRail(1) }),
		tui.On(tui.KeyLeft, func(ke tui.KeyEvent) { s.cycleRail(-1) }),
		tui.On(tui.AnyRune, func(ke tui.KeyEvent) {
			if s.activeFocus() != FocusComposer {
				return
			}
			s.updateComposer(string(ke.Rune))
		}),
		tui.On(tui.KeyBackspace, func(ke tui.KeyEvent) {
			if s.activeFocus() != FocusComposer {
				return
			}
			s.backspaceComposer()
		}),
		tui.On(tui.KeyEnter, func(ke tui.KeyEvent) {
			if s.activeFocus() != FocusComposer {
				return
			}
			s.submitComposer()
		}),
	)
	return keyMap
}

func (s *Shell) activeFocus() FocusPane {
	return focusPaneForIndex(s.focus.Current())
}

func (s *Shell) isFocused(pane FocusPane) bool {
	return s.activeFocus() == pane
}

func (s *Shell) setRail(tab RailTab) {
	s.state.Update(func(state ShellState) ShellState {
		state.ActiveRail = tab
		return state
	})
}

func (s *Shell) cycleRail(delta int) {
	s.state.Update(func(state ShellState) ShellState {
		state.ActiveRail = nextRail(state.ActiveRail, delta)
		return state
	})
}

func (s *Shell) updateComposer(text string) {
	s.state.Update(func(state ShellState) ShellState {
		state.Composer += text
		return state
	})
}

func (s *Shell) backspaceComposer() {
	s.state.Update(func(state ShellState) ShellState {
		if state.Composer == "" {
			return state
		}
		runes := []rune(state.Composer)
		state.Composer = string(runes[:len(runes)-1])
		return state
	})
}

func (s *Shell) submitComposer() {
	s.state.Update(func(state ShellState) ShellState {
		text := strings.TrimSpace(state.Composer)
		if text == "" {
			return state
		}
		state.Transcript = append(state.Transcript, TranscriptEntry{
			Speaker: "you",
			Kind:    "draft",
			Text:    text,
		})
		state.Composer = ""
		return state
	})
}

func focusClass(active bool) string {
	if active {
		return "border-cyan"
	}
	return "border-black"
}

func focusLabel(active bool) string {
	if active {
		return "focused"
	}
	return "idle"
}

func railTabClass(active bool) string {
	if active {
		return "text-cyan font-bold"
	}
	return "font-dim"
}

func composerText(text string) string {
	if text == "" {
		return "Type a draft instruction, Enter records it locally"
	}
	return text
}

func paneNames() string {
	return "Tab: focus | Shift+Tab: reverse | Ctrl+M/Y/W/B: rails | q/Esc/Ctrl+C: quit"
}

type TopBarView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *TopBarView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *TopBarView) GetRoot() *tui.Element { return v.Root }

func (v *TopBarView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *TopBarView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *TopBarView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *TopBarView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*TopBarView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*TopBarView)(nil)

var _ tui.AppUnbinder = (*TopBarView)(nil)

var _ tui.PropsUpdater = (*TopBarView)(nil)

func TopBar(state ShellState) *TopBarView {
	var view TopBarView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithFlexShrink(0),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_2 := tui.New(
		tui.WithText("foxctl_tui"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(state.Workspace),
	)
	__tui_1.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText("|"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_1.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText(state.EpicTitle),
	)
	__tui_1.AddChild(__tui_5)
	__tui_6 := tui.New(
		tui.WithText(state.EpicStatus),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Bold()),
	)
	__tui_1.AddChild(__tui_6)
	__tui_0.AddChild(__tui_1)
	__tui_7 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_8 := tui.New(
		tui.WithText(state.Assistant.Role),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_7.AddChild(__tui_8)
	__tui_9 := tui.New(
		tui.WithText(state.Assistant.Name),
	)
	__tui_7.AddChild(__tui_9)
	__tui_10 := tui.New(
		tui.WithText(fmt.Sprintf("%s/%s", state.Assistant.Provider, state.Assistant.Model)),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_7.AddChild(__tui_10)
	__tui_0.AddChild(__tui_7)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = TopBarView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type TranscriptPaneView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *TranscriptPaneView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *TranscriptPaneView) GetRoot() *tui.Element { return v.Root }

func (v *TranscriptPaneView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *TranscriptPaneView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *TranscriptPaneView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *TranscriptPaneView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*TranscriptPaneView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*TranscriptPaneView)(nil)

var _ tui.AppUnbinder = (*TranscriptPaneView)(nil)

var _ tui.PropsUpdater = (*TranscriptPaneView)(nil)

func TranscriptPane(state ShellState, active bool) *TranscriptPaneView {
	var view TranscriptPaneView
	var watchers []tui.Watcher

	__tui_0 := tui.New()
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithFlexShrink(0),
	)
	__tui_2 := tui.New(
		tui.WithText("Transcript"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(focusLabel(active)),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	__tui_4 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithFlexGrow(1),
	)
	for __idx_0, entry := range state.Transcript {
		_ = __idx_0
		__tui_6 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithBorder(tui.BorderSingle),
			tui.WithPadding(1),
		)
		__tui_7 := tui.New(
			tui.WithText(fmt.Sprintf("%s [%s]", entry.Speaker, entry.Kind)),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_6.AddChild(__tui_7)
		__tui_8 := tui.New(
			tui.WithText(entry.Text),
		)
		__tui_6.AddChild(__tui_8)
		__tui_5.AddChild(__tui_6)
	}
	__tui_0.AddChild(__tui_5)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = TranscriptPaneView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type ComposerPaneView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ComposerPaneView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ComposerPaneView) GetRoot() *tui.Element { return v.Root }

func (v *ComposerPaneView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ComposerPaneView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ComposerPaneView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ComposerPaneView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ComposerPaneView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ComposerPaneView)(nil)

var _ tui.AppUnbinder = (*ComposerPaneView)(nil)

var _ tui.PropsUpdater = (*ComposerPaneView)(nil)

func ComposerPane(state ShellState, active bool) *ComposerPaneView {
	var view ComposerPaneView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithHeight(5),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
	)
	__tui_2 := tui.New(
		tui.WithText("Composer"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(focusLabel(active)),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	__tui_4 := tui.New(
		tui.WithText(composerText(state.Composer)),
	)
	__tui_0.AddChild(__tui_4)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = ComposerPaneView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type RailTabsView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *RailTabsView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *RailTabsView) GetRoot() *tui.Element { return v.Root }

func (v *RailTabsView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *RailTabsView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *RailTabsView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *RailTabsView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*RailTabsView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*RailTabsView)(nil)

var _ tui.AppUnbinder = (*RailTabsView)(nil)

var _ tui.PropsUpdater = (*RailTabsView)(nil)

func RailTabs(active RailTab) *RailTabsView {
	var view RailTabsView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithFlexShrink(0),
	)
	for __idx_0, tab := range railTabs() {
		_ = __idx_0
		__tui_1 := tui.New(
			tui.WithText(tab.Label()),
		)
		__tui_0.AddChild(__tui_1)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = RailTabsView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type MemoryRailView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *MemoryRailView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *MemoryRailView) GetRoot() *tui.Element { return v.Root }

func (v *MemoryRailView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *MemoryRailView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *MemoryRailView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *MemoryRailView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*MemoryRailView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*MemoryRailView)(nil)

var _ tui.AppUnbinder = (*MemoryRailView)(nil)

var _ tui.PropsUpdater = (*MemoryRailView)(nil)

func MemoryRail(items []MemorySummary) *MemoryRailView {
	var view MemoryRailView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithFlexGrow(1),
	)
	for __idx_0, item := range items {
		_ = __idx_0
		__tui_1 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithBorder(tui.BorderSingle),
			tui.WithPadding(1),
		)
		__tui_2 := tui.New(
			tui.WithText(item.Title),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_1.AddChild(__tui_2)
		__tui_3 := tui.New(
			tui.WithText(item.Summary),
		)
		__tui_1.AddChild(__tui_3)
		__tui_0.AddChild(__tui_1)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = MemoryRailView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type ContinuityRailView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ContinuityRailView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ContinuityRailView) GetRoot() *tui.Element { return v.Root }

func (v *ContinuityRailView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ContinuityRailView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ContinuityRailView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ContinuityRailView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ContinuityRailView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ContinuityRailView)(nil)

var _ tui.AppUnbinder = (*ContinuityRailView)(nil)

var _ tui.PropsUpdater = (*ContinuityRailView)(nil)

func ContinuityRail(item ContinuitySummary) *ContinuityRailView {
	var view ContinuityRailView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithFlexGrow(1),
	)
	__tui_1 := tui.New(
		tui.WithText(item.EpicID),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(fmt.Sprintf("status: %s", item.Status)),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(item.Boundary),
	)
	__tui_0.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText("Next"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_5)
	__tui_6 := tui.New(
		tui.WithText(item.Next),
	)
	__tui_0.AddChild(__tui_6)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = ContinuityRailView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type WorkersRailView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *WorkersRailView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *WorkersRailView) GetRoot() *tui.Element { return v.Root }

func (v *WorkersRailView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *WorkersRailView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *WorkersRailView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *WorkersRailView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*WorkersRailView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*WorkersRailView)(nil)

var _ tui.AppUnbinder = (*WorkersRailView)(nil)

var _ tui.PropsUpdater = (*WorkersRailView)(nil)

func WorkersRail(workers []WorkerSummary, active bool) *WorkersRailView {
	var view WorkersRailView
	var watchers []tui.Watcher

	__tui_0 := tui.New()
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
	)
	__tui_2 := tui.New(
		tui.WithText("Workers"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(focusLabel(active)),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	for __idx_0, worker := range workers {
		_ = __idx_0
		__tui_4 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithBorder(tui.BorderSingle),
			tui.WithPadding(1),
		)
		__tui_5 := tui.New(
			tui.WithText(fmt.Sprintf("%s: %s", worker.Name, worker.Status)),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_4.AddChild(__tui_5)
		__tui_6 := tui.New(
			tui.WithText(worker.Task),
		)
		__tui_4.AddChild(__tui_6)
		__tui_0.AddChild(__tui_4)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = WorkersRailView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type TaskRailView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *TaskRailView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *TaskRailView) GetRoot() *tui.Element { return v.Root }

func (v *TaskRailView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *TaskRailView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *TaskRailView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *TaskRailView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*TaskRailView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*TaskRailView)(nil)

var _ tui.AppUnbinder = (*TaskRailView)(nil)

var _ tui.PropsUpdater = (*TaskRailView)(nil)

func TaskRail() *TaskRailView {
	var view TaskRailView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithFlexGrow(1),
	)
	__tui_1 := tui.New(
		tui.WithText("Current task"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText("Build Phase 0 shell and prove go-tui generation/build path."),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText("Definition of done"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText("binary builds, generated .gsx committed, focus works, mocked panes visible"),
	)
	__tui_0.AddChild(__tui_5)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = TaskRailView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type RightRailView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *RightRailView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *RightRailView) GetRoot() *tui.Element { return v.Root }

func (v *RightRailView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *RightRailView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *RightRailView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *RightRailView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*RightRailView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*RightRailView)(nil)

var _ tui.AppUnbinder = (*RightRailView)(nil)

var _ tui.PropsUpdater = (*RightRailView)(nil)

func RightRail(state ShellState, railActive bool, workersActive bool) *RightRailView {
	var view RightRailView
	var watchers []tui.Watcher

	var __tui_6 *MemoryRailView
	var __tui_7 *ContinuityRailView
	var __tui_8 *WorkersRailView
	var __tui_9 *TaskRailView
	__tui_0 := tui.New(
		tui.WithWidth(44),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
	)
	__tui_2 := tui.New(
		tui.WithText("Context Rail"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(focusLabel(railActive)),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	__tui_4 := RailTabs(state.ActiveRail)
	__tui_0.AddChild(__tui_4.Root)
	__tui_5 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_5)
	if state.ActiveRail == RailMemory {
		__tui_6 = MemoryRail(state.Memory)
		__tui_0.AddChild(__tui_6.Root)
	} else if state.ActiveRail == RailContinuity {
		__tui_7 = ContinuityRail(state.Continuity)
		__tui_0.AddChild(__tui_7.Root)
	} else if state.ActiveRail == RailWorkers {
		__tui_8 = WorkersRail(state.Workers, workersActive)
		__tui_0.AddChild(__tui_8.Root)
	} else {
		__tui_9 = TaskRail()
		__tui_0.AddChild(__tui_9.Root)
	}

	watchers = append(watchers, __tui_4.GetWatchers()...)
	if __tui_6 != nil {
		watchers = append(watchers, __tui_6.GetWatchers()...)
	}
	if __tui_7 != nil {
		watchers = append(watchers, __tui_7.GetWatchers()...)
	}
	if __tui_8 != nil {
		watchers = append(watchers, __tui_8.GetWatchers()...)
	}
	if __tui_9 != nil {
		watchers = append(watchers, __tui_9.GetWatchers()...)
	}

	__bindApp := func(app *tui.App) {
		if binder, ok := any(__tui_4).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
		if __tui_6 != nil {
			if binder, ok := any(__tui_6).(tui.AppBinder); ok {
				binder.BindApp(app)
			}
		}
		if __tui_7 != nil {
			if binder, ok := any(__tui_7).(tui.AppBinder); ok {
				binder.BindApp(app)
			}
		}
		if __tui_8 != nil {
			if binder, ok := any(__tui_8).(tui.AppBinder); ok {
				binder.BindApp(app)
			}
		}
		if __tui_9 != nil {
			if binder, ok := any(__tui_9).(tui.AppBinder); ok {
				binder.BindApp(app)
			}
		}
	}

	__unbindApp := func() {
		if unbinder, ok := any(__tui_4).(tui.AppUnbinder); ok {
			unbinder.UnbindApp()
		}
		if __tui_6 != nil {
			if unbinder, ok := any(__tui_6).(tui.AppUnbinder); ok {
				unbinder.UnbindApp()
			}
		}
		if __tui_7 != nil {
			if unbinder, ok := any(__tui_7).(tui.AppUnbinder); ok {
				unbinder.UnbindApp()
			}
		}
		if __tui_8 != nil {
			if unbinder, ok := any(__tui_8).(tui.AppUnbinder); ok {
				unbinder.UnbindApp()
			}
		}
		if __tui_9 != nil {
			if unbinder, ok := any(__tui_9).(tui.AppUnbinder); ok {
				unbinder.UnbindApp()
			}
		}
	}

	view = RightRailView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type FooterView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *FooterView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *FooterView) GetRoot() *tui.Element { return v.Root }

func (v *FooterView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *FooterView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *FooterView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *FooterView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*FooterView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*FooterView)(nil)

var _ tui.AppUnbinder = (*FooterView)(nil)

var _ tui.PropsUpdater = (*FooterView)(nil)

func Footer() *FooterView {
	var view FooterView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithFlexShrink(0),
	)
	__tui_1 := tui.New(
		tui.WithText(paneNames()),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_1)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = FooterView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

func (s *Shell) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithHeightPercent(100.00),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := TopBar(s.state.Get())
	__tui_0.AddChild(__tui_1.Root)
	__tui_2 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithFlexGrow(1),
		tui.WithPadding(1),
	)
	__tui_3 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithFlexGrow(1),
	)
	__tui_4 := TranscriptPane(s.state.Get(), s.isFocused(FocusTranscript))
	__tui_3.AddChild(__tui_4.Root)
	__tui_5 := ComposerPane(s.state.Get(), s.isFocused(FocusComposer))
	__tui_3.AddChild(__tui_5.Root)
	__tui_2.AddChild(__tui_3)
	__tui_6 := RightRail(s.state.Get(), s.isFocused(FocusRail), s.isFocused(FocusWorkers))
	__tui_2.AddChild(__tui_6.Root)
	__tui_0.AddChild(__tui_2)
	__tui_7 := Footer()
	__tui_0.AddChild(__tui_7.Root)

	return __tui_0
}

func (s *Shell) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*Shell)
	if !ok {
		return
	}
	s.focus = f.focus
}

var _ tui.PropsUpdater = (*Shell)(nil)

func (s *Shell) BindApp(app *tui.App) {
	if s.state != nil {
		s.state.BindApp(app)
	}
	if s.transcriptFocus != nil {
		s.transcriptFocus.BindApp(app)
	}
	if s.composerFocus != nil {
		s.composerFocus.BindApp(app)
	}
	if s.railFocus != nil {
		s.railFocus.BindApp(app)
	}
	if s.workersFocus != nil {
		s.workersFocus.BindApp(app)
	}
}

var _ tui.AppBinder = (*Shell)(nil)

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*Shell)(nil)
)
