// Command agentctl-mail sends messages to agent inboxes for human-in-the-loop
// communication with running Claude Code sessions.
//
// Usage:
//
//	agentctl-mail "Subject" "Body"
//	agentctl-mail -p 1 "URGENT" "Stop and review this"
//	agentctl-mail --ack "Review needed" "Check the API changes"
//	agentctl-mail --to claude "Question" "How should we handle auth?"
//
// The command automatically detects the workspace using:
//  1. AGENTCTL_WORKSPACE env var
//  2. CLAUDE_PROJECT_DIR env var
//  3. Git root from current directory
//  4. Current working directory
package main

import (
	"context"
	"flag"
	"fmt"
	"os"

	"github.com/rs/zerolog"

	"github.com/jkatigb/agentctl/internal/domain/agent"
	"github.com/jkatigb/agentctl/internal/platform/config"
	wsutil "github.com/jkatigb/agentctl/internal/platform/workspace"
	"github.com/jkatigb/agentctl/internal/protocol"
	"github.com/jkatigb/agentctl/internal/storage/blackboard"
)

func main() {
	logger := zerolog.New(os.Stderr).With().Timestamp().Logger()

	// Flags
	priority := flag.Int("p", 3, "Priority level (1=highest, 5=lowest)")
	ackRequired := flag.Bool("ack", false, "Require acknowledgment from agent")
	recipient := flag.String("to", "overseer", "Recipient (default: overseer)")
	sender := flag.String("from", "human", "Sender name (default: human)")
	kind := flag.String("kind", "instruction", "Message kind: instruction, info, alert, review_request")
	workspace := flag.String("workspace", "", "Workspace path (auto-detected if not specified)")
	quiet := flag.Bool("q", false, "Quiet mode - only output message ID")

	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: %s [options] <subject> [body]\n\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "Send messages to a running Claude Code session via the overseer inbox.\n\n")
		fmt.Fprintf(os.Stderr, "Examples:\n")
		fmt.Fprintf(os.Stderr, "  %s \"Priority change\" \"Focus on auth bug first\"\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "  %s -p 1 \"STOP\" \"Pause and review this issue\"\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "  %s --ack \"Review needed\" \"Check the API changes\"\n\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "Options:\n")
		flag.PrintDefaults()
	}

	flag.Parse()

	args := flag.Args()
	if len(args) < 1 {
		flag.Usage()
		os.Exit(1)
	}

	subject := args[0]
	body := ""
	if len(args) > 1 {
		body = args[1]
	}

	// If ack required, append reminder to body
	if *ackRequired {
		ackReminder := "\n\n---\n⚠️ **Acknowledgment Required**: Please confirm receipt with \"(message received)\" in your response."
		body += ackReminder
	}

	// Detect workspace
	ws := *workspace
	if ws == "" {
		ws = wsutil.Detect("")
	}
	if ws == "" {
		logger.Error().
			Str("workspace_flag", *workspace).
			Msg("could not detect workspace (try --workspace flag)")
		_ = protocol.WriteError(os.Stdout, "agentctl.mail.send", protocol.ErrorCodeEARG, "workspace not detected", nil)
		os.Exit(1)
	}

	// Parse kind
	msgKind := parseKind(*kind)

	// Send message
	ctx := context.Background()
	msgID, err := sendMessage(ctx, ws, agent.BoardMessage{
		Sender:      *sender,
		Recipient:   *recipient,
		Subject:     subject,
		Body:        body,
		Priority:    *priority,
		Kind:        msgKind,
		AckRequired: *ackRequired,
	})
	if err != nil {
		logger.Error().
			Str("workspace", ws).
			Str("recipient", *recipient).
			Err(err).
			Msg("failed to send message")
		_ = protocol.WriteError(os.Stdout, "agentctl.mail.send", protocol.ErrorCodeERuntime, err.Error(), nil, protocol.WithWorkspace(ws))
		os.Exit(1)
	}

	if *quiet {
		err = protocol.WriteOK(os.Stdout, "agentctl.mail.send", map[string]any{
			"message_id": msgID,
		}, protocol.WithWorkspace(ws))
	} else {
		err = protocol.WriteOK(os.Stdout, "agentctl.mail.send", map[string]any{
			"message_id": msgID,
			"recipient":  *recipient,
			"workspace":  ws,
			"priority":   *priority,
			"ack":        *ackRequired,
			"kind":       msgKind,
		}, protocol.WithWorkspace(ws))
	}
	if err != nil {
		logger.Error().Err(err).Msg("failed to write envelope")
		os.Exit(1)
	}
}

func sendMessage(ctx context.Context, workspaceID string, msg agent.BoardMessage) (string, error) {
	cfg, err := config.Load(ctx)
	if err != nil {
		return "", fmt.Errorf("load config: %w", err)
	}

	store, err := blackboard.OpenBoardStore(ctx, cfg.Storage.Root)
	if err != nil {
		return "", fmt.Errorf("open board store: %w", err)
	}
	defer store.Close()

	// Set workspace and stream (ID is auto-generated by SendMessage)
	msg.WorkspaceID = workspaceID
	msg.Stream = "coordination"

	if err := store.SendMessage(ctx, &msg); err != nil {
		return "", fmt.Errorf("send message: %w", err)
	}

	return msg.ID, nil
}

func parseKind(s string) agent.BoardMessageKind {
	switch s {
	case "instruction":
		return agent.BoardMessageKindInstruction
	case "info":
		return agent.BoardMessageKindInfo
	case "alert":
		return agent.BoardMessageKindAlert
	case "review_request":
		return agent.BoardMessageKindReviewRequest
	default:
		return agent.BoardMessageKindInstruction
	}
}
