apiVersion: v1
kind: Secret
metadata:
  name: gui-auth-gateway-secrets
  namespace: foxctl
  labels:
    app.kubernetes.io/name: foxctl
    app.kubernetes.io/component: gui-auth-gateway
type: Opaque
stringData:
  better-auth-secret: "replace-with-openssl-rand-base64-32-output"
  smtp-user: "replace-me"
  smtp-pass: "replace-me"
