package contextplane

import (
	"strings"
	"testing"
	"time"

	"github.com/joshka0/foxctl/internal/context/transcriptpipeline/history"
)

func TestPlanTranscriptDreamNoteRendersStableObsidianContract(t *testing.T) {
	now := time.Date(2026, 5, 24, 10, 30, 0, 0, time.UTC)
	note, err := PlanTranscriptDreamNote(TranscriptDreamNoteInput{
		Project:          "foxctl",
		WorkspaceID:      "foxctl",
		Provider:         "codex",
		SessionID:        "sess-1",
		SourceDigest:     "sha256:source",
		Now:              now,
		Title:            "Dream service memory layer",
		DistilledSummary: "The dream pass should preserve reviewable memory lessons without copying transcript turns.",
		BlurredMechanisms: []TranscriptDreamMechanism{{
			Name:       "Review-gated distillation",
			Summary:    "A transcript-derived signal becomes an abstract note only after the raw exchange is compressed into evidence-bound claims.",
			Confidence: 0.82,
			Tags:       []string{"review_gate", "distillation"},
		}},
		SourceRefs: []TranscriptDreamSourceRef{{
			RecordID:        "transcript_history:sess-1:insight:abc123",
			Kind:            history.HistoryRecordKindInsight,
			SessionIDs:      []string{"sess-1"},
			SourceStartedAt: time.Date(2026, 5, 23, 9, 0, 0, 0, time.UTC),
			Summary:         "Use transcript dreams as reviewed memory seeds.",
			EvidenceRefs:    []string{"path:internal/context/contextplane/transcript_dream.go"},
		}},
		Review: TranscriptDreamReview{
			Reviewer:    "human",
			GeneratedBy: "dream-service",
			Notes:       []string{"Check for over-specific mechanism leakage before promotion."},
		},
	})
	if err != nil {
		t.Fatalf("PlanTranscriptDreamNote() error = %v", err)
	}

	if note.SourceLane != "transcript_dream" {
		t.Fatalf("SourceLane=%q", note.SourceLane)
	}
	if note.DraftPath != "inbox/drafted-from-foxctl/dreams/foxctl/2026-05-24/dream-service-memory-layer-f7c014293a37.md" {
		t.Fatalf("DraftPath=%q", note.DraftPath)
	}
	want := `---
type: "memory"
status: "draft"
trust: "raw"
source_lane: "transcript_dream"
project: "foxctl"
workspace_id: "foxctl"
provider: "codex"
session_id: "sess-1"
source_digest: "sha256:source"
dedupe_key: "transcript_dream:151bdb5040899401f31ac8bc8dfe4266798cd7896e3b43b748b8f7c014293a37"
created_at: "2026-05-24T10:30:00Z"
review_status: "needs_review"
review_required: "true"
reviewer: "human"
generated_by: "dream-service"
mechanism_tags:
  - "distillation"
  - "review_gate"
source_refs:
  - "transcript_history:sess-1:insight:abc123"
source_sessions:
  - "sess-1"
tags:
  - "foxctl/dream"
  - "foxctl/review-required"
  - "foxctl/transcript-dream"
---

# Dream service memory layer

## Distilled Summary
The dream pass should preserve reviewable memory lessons without copying transcript turns.

## Blurred Mechanisms
- **Review-gated distillation**: A transcript-derived signal becomes an abstract note only after the raw exchange is compressed into evidence-bound claims. _(confidence 0.82)_

## Source References
- ` + "`transcript_history:sess-1:insight:abc123`" + ` (insight) from 2026-05-23T09:00:00Z: Use transcript dreams as reviewed memory seeds.

## Review Metadata
- Status: needs_review
- Review required: true
- Reviewer: human
- Generated by: dream-service
- Note: Check for over-specific mechanism leakage before promotion.
`
	if note.Content != want {
		t.Fatalf("content mismatch\nwant:\n%s\ngot:\n%s", want, note.Content)
	}
}

func TestPlanTranscriptDreamNoteSanitizesDraftPath(t *testing.T) {
	note, err := PlanTranscriptDreamNote(TranscriptDreamNoteInput{
		Project:          "../Fox Ctl Workspace!!",
		Now:              time.Date(2026, 5, 24, 0, 0, 0, 0, time.UTC),
		Title:            "../../Dream: raw transcript? no",
		DistilledSummary: "Only distilled content is allowed.",
		BlurredMechanisms: []TranscriptDreamMechanism{{
			Name:    "Abstract owner",
			Summary: "Durable behavior is described without copying dialogue.",
		}},
		SourceRefs: []TranscriptDreamSourceRef{{RecordID: "record/../one", Summary: "A summarized record."}},
	})
	if err != nil {
		t.Fatalf("PlanTranscriptDreamNote() error = %v", err)
	}

	if !strings.HasPrefix(note.DraftPath, "inbox/drafted-from-foxctl/dreams/fox-ctl-workspace/2026-05-24/") {
		t.Fatalf("DraftPath=%q", note.DraftPath)
	}
	if strings.Contains(note.DraftPath, "..") || strings.Contains(note.DraftPath, "\\") || strings.Contains(note.DraftPath, " ") {
		t.Fatalf("DraftPath not sanitized: %q", note.DraftPath)
	}
}

func TestPlanTranscriptDreamNoteRequiresFrontmatterInputs(t *testing.T) {
	base := TranscriptDreamNoteInput{
		Project:          "foxctl",
		Now:              time.Date(2026, 5, 24, 0, 0, 0, 0, time.UTC),
		DistilledSummary: "A distilled summary.",
		BlurredMechanisms: []TranscriptDreamMechanism{{
			Name:    "Mechanism",
			Summary: "A blurred mechanism.",
		}},
		SourceRefs: []TranscriptDreamSourceRef{{RecordID: "record-1"}},
	}
	tests := []struct {
		name  string
		input TranscriptDreamNoteInput
	}{
		{name: "summary", input: func() TranscriptDreamNoteInput { in := base; in.DistilledSummary = ""; return in }()},
		{name: "mechanism", input: func() TranscriptDreamNoteInput { in := base; in.BlurredMechanisms = nil; return in }()},
		{name: "source", input: func() TranscriptDreamNoteInput { in := base; in.SourceRefs = nil; return in }()},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if _, err := PlanTranscriptDreamNote(tt.input); err == nil {
				t.Fatal("expected error")
			}
		})
	}

	note, err := PlanTranscriptDreamNote(base)
	if err != nil {
		t.Fatalf("PlanTranscriptDreamNote() error = %v", err)
	}
	for _, field := range []string{
		`type: "memory"`,
		`status: "draft"`,
		`source_lane: "transcript_dream"`,
		`project: "foxctl"`,
		`dedupe_key: "transcript_dream:`,
		`review_status: "needs_review"`,
		`review_required: "true"`,
		`source_refs:`,
	} {
		if !strings.Contains(note.Content, field) {
			t.Fatalf("missing frontmatter field %q in:\n%s", field, note.Content)
		}
	}
}
