package contextplane

import (
	"strings"
	"testing"
	"time"

	"github.com/joshka0/foxctl/internal/context/transcriptpipeline/history"
)

func TestPlanTranscriptDreamNoteRendersStableObsidianContract(t *testing.T) {
	now := time.Date(2026, 5, 24, 10, 30, 0, 0, time.UTC)
	note, err := PlanTranscriptDreamNote(TranscriptDreamNoteInput{
		Project:          "foxctl",
		WorkspaceID:      "foxctl",
		Provider:         "codex",
		SessionID:        "sess-1",
		SourceDigest:     "sha256:source",
		Now:              now,
		Title:            "Dream service memory layer",
		DistilledSummary: "The dream pass should preserve reviewable memory lessons without copying transcript turns.",
		BlurredMechanisms: []TranscriptDreamMechanism{{
			Name:       "Review-gated distillation",
			Summary:    "A transcript-derived signal becomes an abstract note only after the raw exchange is compressed into evidence-bound claims.",
			Confidence: 0.82,
			Tags:       []string{"review_gate", "distillation"},
		}},
		SourceRefs: []TranscriptDreamSourceRef{{
			RecordID:        "transcript_history:sess-1:insight:abc123",
			Kind:            history.HistoryRecordKindInsight,
			SessionIDs:      []string{"sess-1"},
			SourceStartedAt: time.Date(2026, 5, 23, 9, 0, 0, 0, time.UTC),
			Summary:         "Use transcript dreams as reviewed memory seeds.",
			EvidenceRefs:    []string{"path:internal/context/contextplane/transcript_dream.go"},
		}},
		Review: TranscriptDreamReview{
			Reviewer:    "human",
			GeneratedBy: "dream-service",
			Notes:       []string{"Check for over-specific mechanism leakage before promotion."},
		},
	})
	if err != nil {
		t.Fatalf("PlanTranscriptDreamNote() error = %v", err)
	}

	if note.SourceLane != "transcript_dream" {
		t.Fatalf("SourceLane=%q", note.SourceLane)
	}
	if note.DraftPath != "inbox/drafted-from-foxctl/dreams/foxctl/2026-05-24/dream-service-memory-layer-f7c014293a37.md" {
		t.Fatalf("DraftPath=%q", note.DraftPath)
	}
	want := `---
type: "memory"
status: "draft"
trust: "raw"
source_lane: "transcript_dream"
project: "foxctl"
workspace_id: "foxctl"
provider: "codex"
session_id: "sess-1"
source_digest: "sha256:source"
dedupe_key: "transcript_dream:151bdb5040899401f31ac8bc8dfe4266798cd7896e3b43b748b8f7c014293a37"
created_at: "2026-05-24T10:30:00Z"
review_status: "needs_review"
review_required: "true"
reviewer: "human"
generated_by: "dream-service"
mechanism_tags:
  - "distillation"
  - "review_gate"
source_refs:
  - "transcript_history:sess-1:insight:abc123"
source_sessions:
  - "sess-1"
tags:
  - "foxctl/dream"
  - "foxctl/review-required"
  - "foxctl/transcript-dream"
---

# Dream service memory layer

## Distilled Summary
The dream pass should preserve reviewable memory lessons without copying transcript turns.

## Blurred Mechanisms
- **Review-gated distillation**: A transcript-derived signal becomes an abstract note only after the raw exchange is compressed into evidence-bound claims. _(confidence 0.82)_

## Source References
- ` + "`transcript_history:sess-1:insight:abc123`" + ` (insight) from 2026-05-23T09:00:00Z: Use transcript dreams as reviewed memory seeds.

## Review Metadata
- Status: needs_review
- Review required: true
- Reviewer: human
- Generated by: dream-service
- Note: Check for over-specific mechanism leakage before promotion.
`
	if note.Content != want {
		t.Fatalf("content mismatch\nwant:\n%s\ngot:\n%s", want, note.Content)
	}
}

func TestPlanTranscriptDreamNoteSanitizesDraftPath(t *testing.T) {
	note, err := PlanTranscriptDreamNote(TranscriptDreamNoteInput{
		Project:          "../Fox Ctl Workspace!!",
		Now:              time.Date(2026, 5, 24, 0, 0, 0, 0, time.UTC),
		Title:            "../../Dream: raw transcript? no",
		DistilledSummary: "Only distilled content is allowed.",
		BlurredMechanisms: []TranscriptDreamMechanism{{
			Name:    "Abstract owner",
			Summary: "Durable behavior is described without copying dialogue.",
		}},
		SourceRefs: []TranscriptDreamSourceRef{{RecordID: "record/../one", Summary: "A summarized record."}},
	})
	if err != nil {
		t.Fatalf("PlanTranscriptDreamNote() error = %v", err)
	}

	if !strings.HasPrefix(note.DraftPath, "inbox/drafted-from-foxctl/dreams/fox-ctl-workspace/2026-05-24/") {
		t.Fatalf("DraftPath=%q", note.DraftPath)
	}
	if strings.Contains(note.DraftPath, "..") || strings.Contains(note.DraftPath, "\\") || strings.Contains(note.DraftPath, " ") {
		t.Fatalf("DraftPath not sanitized: %q", note.DraftPath)
	}
}

func TestPlanTranscriptDreamNoteRendersAgentBlur(t *testing.T) {
	note, err := PlanTranscriptDreamNote(TranscriptDreamNoteInput{
		Project:          "foxctl",
		WorkspaceID:      "foxctl",
		Provider:         "codex",
		SessionID:        "sess-1",
		SourceDigest:     "sha256:source",
		Now:              time.Date(2026, 5, 24, 10, 30, 0, 0, time.UTC),
		Title:            "You own exactly one file",
		DistilledSummary: "You own exactly one file.",
		BlurredMechanisms: []TranscriptDreamMechanism{{
			Name:    "direction",
			Summary: "You own exactly one file.",
			Tags:    []string{"direction"},
		}},
		SourceRefs: []TranscriptDreamSourceRef{{RecordID: "record-1", Summary: "You own exactly one file."}},
		AgentBlur: &TranscriptDreamAgentBlur{
			Agent:          "pi",
			AbstractSchema: "bounded ownership reduces coordination ambiguity by assigning one actor one explicit responsibility",
			MechanismTags:  []string{"bounded_ownership", "coordination_control"},
			Confidence:     0.86,
			LeakageRisk:    0.02,
		},
	})
	if err != nil {
		t.Fatalf("PlanTranscriptDreamNote() error = %v", err)
	}
	for _, want := range []string{
		`agent_blurred: "true"`,
		`blur_agent: "pi"`,
		`foxctl/agent-blurred`,
		`## Agent Blurred Mechanism`,
		`bounded ownership reduces coordination ambiguity`,
		`Mechanism tags: bounded_ownership, coordination_control`,
	} {
		if !strings.Contains(note.Content, want) {
			t.Fatalf("agent blur note missing %q:\n%s", want, note.Content)
		}
	}
}

func TestBuildTranscriptDreamBlurAgentPromptInputHidesConcreteSourceRefs(t *testing.T) {
	input := TranscriptDreamNoteInput{
		Project:          "/repo/foxctl",
		WorkspaceID:      "repo-foxctl",
		Provider:         "codex",
		SessionID:        "sess-1",
		SourceDigest:     "sha256:source",
		Title:            "You own exactly one file",
		DistilledSummary: "You own exactly one file.",
		BlurredMechanisms: []TranscriptDreamMechanism{
			{Name: "direction", Summary: "You own exactly one file."},
			{Name: "command", Summary: "<user_shell_command> git status </user_shell_command>"},
		},
		SourceRefs: []TranscriptDreamSourceRef{{
			RecordID:     "record-1",
			SessionIDs:   []string{"sess-1"},
			Summary:      "The assistant repeated the one-file ownership rule.",
			EvidenceRefs: []string{"file:/home/dev/.codex/sessions/session.jsonl"},
		}},
	}
	got, err := BuildTranscriptDreamBlurAgentPromptInput(input)
	if err != nil {
		t.Fatalf("BuildTranscriptDreamBlurAgentPromptInput() error = %v", err)
	}
	if got.ID != "transcript-dream" {
		t.Fatalf("ID=%q want generic transcript-dream", got.ID)
	}
	if len(got.SourceRefs) != 0 {
		t.Fatalf("agent prompt should not expose concrete source refs: %#v", got.SourceRefs)
	}
	for _, want := range []string{"record-1", "sess-1", "git status"} {
		if !containsString(got.ForbiddenTerms, want) {
			t.Fatalf("forbidden_terms missing %q: %v", want, got.ForbiddenTerms)
		}
	}
	if !strings.Contains(got.LiteralText, "git status") {
		t.Fatalf("literal text should include noisy material for forgetting:\n%s", got.LiteralText)
	}
	if !strings.Contains(BuildBlurredMechanismSchema(got.Shape), "discard command and output noise") {
		t.Fatalf("shape does not describe transcript-noise blurring:\n%s", BuildBlurredMechanismSchema(got.Shape))
	}
}

func TestApplyTranscriptDreamAgentBlurRejectsLiteralLeakage(t *testing.T) {
	input := TranscriptDreamNoteInput{
		Project:          "foxctl",
		DistilledSummary: "You own exactly one file.",
		BlurredMechanisms: []TranscriptDreamMechanism{{
			Name:    "direction",
			Summary: "You own exactly one file.",
		}},
		SourceRefs: []TranscriptDreamSourceRef{{RecordID: "record-1"}},
	}
	promptInput, err := BuildTranscriptDreamBlurAgentPromptInput(input)
	if err != nil {
		t.Fatalf("BuildTranscriptDreamBlurAgentPromptInput() error = %v", err)
	}
	got, validation := ApplyTranscriptDreamAgentBlur(input, promptInput, "pi", MemoryBlurAgentOutput{
		AbstractSchema: "You own exactly one file as a coordination structure",
		MechanismTags:  []string{"coordination_structure"},
		Confidence:     0.8,
		LeakageRisk:    0.2,
	})
	if validation.Valid {
		t.Fatal("validation should reject leaked literal title")
	}
	if got.AgentBlur != nil {
		t.Fatalf("rejected blur should not attach to note input: %#v", got.AgentBlur)
	}
}

func TestPlanTranscriptDreamNoteRequiresFrontmatterInputs(t *testing.T) {
	base := TranscriptDreamNoteInput{
		Project:          "foxctl",
		Now:              time.Date(2026, 5, 24, 0, 0, 0, 0, time.UTC),
		DistilledSummary: "A distilled summary.",
		BlurredMechanisms: []TranscriptDreamMechanism{{
			Name:    "Mechanism",
			Summary: "A blurred mechanism.",
		}},
		SourceRefs: []TranscriptDreamSourceRef{{RecordID: "record-1"}},
	}
	tests := []struct {
		name  string
		input TranscriptDreamNoteInput
	}{
		{name: "summary", input: func() TranscriptDreamNoteInput { in := base; in.DistilledSummary = ""; return in }()},
		{name: "mechanism", input: func() TranscriptDreamNoteInput { in := base; in.BlurredMechanisms = nil; return in }()},
		{name: "source", input: func() TranscriptDreamNoteInput { in := base; in.SourceRefs = nil; return in }()},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if _, err := PlanTranscriptDreamNote(tt.input); err == nil {
				t.Fatal("expected error")
			}
		})
	}

	note, err := PlanTranscriptDreamNote(base)
	if err != nil {
		t.Fatalf("PlanTranscriptDreamNote() error = %v", err)
	}
	for _, field := range []string{
		`type: "memory"`,
		`status: "draft"`,
		`source_lane: "transcript_dream"`,
		`project: "foxctl"`,
		`dedupe_key: "transcript_dream:`,
		`review_status: "needs_review"`,
		`review_required: "true"`,
		`source_refs:`,
	} {
		if !strings.Contains(note.Content, field) {
			t.Fatalf("missing frontmatter field %q in:\n%s", field, note.Content)
		}
	}
}
