package companion

import (
	"fmt"
	"strings"
)

// SQLDialect captures SQL syntax differences for companion memory portability.
type SQLDialect interface {
	AutoIncrement() string
	TimestampType() string
	TimestampNow() string
	JSONExtract(col, path string) string
	CreateFTS5(table, content, rowid string, columns []string) string
	Placeholder(n int) string
}

// SQLiteDialect implements SQLDialect for SQLite.
type SQLiteDialect struct{}

// AutoIncrement returns SQLite auto-increment token for PK columns.
func (SQLiteDialect) AutoIncrement() string { return "INTEGER PRIMARY KEY AUTOINCREMENT" }

// TimestampType returns SQLite timestamp column type.
func (SQLiteDialect) TimestampType() string { return "TEXT" }

// TimestampNow returns a portable current timestamp expression.
func (SQLiteDialect) TimestampNow() string { return "CURRENT_TIMESTAMP" }

// JSONExtract returns a JSON text extraction expression for SQLite.
func (SQLiteDialect) JSONExtract(col, path string) string {
	return fmt.Sprintf("json_extract(%s, '$.%s')", col, sanitizeJSONPath(path))
}

// CreateFTS5 returns SQLite FTS5 virtual table creation SQL.
func (SQLiteDialect) CreateFTS5(table, content, rowid string, columns []string) string {
	return fmt.Sprintf(
		"CREATE VIRTUAL TABLE IF NOT EXISTS %s USING fts5(%s, content='%s', content_rowid='%s')",
		table,
		strings.Join(columns, ", "),
		content,
		rowid,
	)
}

// Placeholder returns the parameter placeholder for SQLite.
// SQLite uses positional "?" placeholders (driver maps by argument order).
func (SQLiteDialect) Placeholder(_ int) string { return "?" }

// PostgresDialect implements SQLDialect for PostgreSQL.
type PostgresDialect struct{}

// AutoIncrement returns PostgreSQL identity token for PK columns.
func (PostgresDialect) AutoIncrement() string { return "BIGINT GENERATED BY DEFAULT AS IDENTITY" }

// TimestampType returns PostgreSQL timestamp column type.
func (PostgresDialect) TimestampType() string { return "TIMESTAMPTZ" }

// TimestampNow returns a portable current timestamp expression.
func (PostgresDialect) TimestampNow() string { return "CURRENT_TIMESTAMP" }

// JSONExtract returns a JSON text extraction expression for PostgreSQL.
func (PostgresDialect) JSONExtract(col, path string) string {
	return fmt.Sprintf("%s->>'%s'", col, sanitizeJSONPath(path))
}

// CreateFTS5 returns SQL for PostgreSQL full-text search compatibility.
func (PostgresDialect) CreateFTS5(table, content, rowid string, columns []string) string {
	contentColumn := ftsDefaultColumn(columns)
	_ = rowid
	return fmt.Sprintf(
		"CREATE INDEX IF NOT EXISTS %s ON %s USING GIN (to_tsvector('simple', %s))",
		postgresFTSIndexName(table),
		content,
		contentColumn,
	)
}

// Placeholder returns the parameter placeholder for PostgreSQL.
func (PostgresDialect) Placeholder(n int) string { return fmt.Sprintf("$%d", n) }

func sanitizeJSONPath(path string) string {
	out := make([]byte, 0, len(path))
	for i := 0; i < len(path); i++ {
		c := path[i]
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' || c == '-' || c == '.' {
			out = append(out, c)
		}
	}
	return string(out)
}

func postgresFTSIndexName(table string) string {
	return fmt.Sprintf("idx_%s_fts", sanitizeIdentifier(table))
}

func ftsDefaultColumn(columns []string) string {
	for _, column := range columns {
		if column == "" {
			continue
		}
		name := strings.SplitN(column, " ", 2)[0]
		if strings.Contains(strings.ToUpper(column), "UNINDEXED") {
			continue
		}
		return sanitizeIdentifier(name)
	}
	if len(columns) > 0 {
		name := strings.SplitN(columns[0], " ", 2)[0]
		return sanitizeIdentifier(name)
	}
	return "fact_text"
}

func sanitizeIdentifier(identifier string) string {
	out := make([]byte, 0, len(identifier))
	for i := 0; i < len(identifier); i++ {
		c := identifier[i]
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' {
			out = append(out, c)
		}
	}
	return string(out)
}
